### ISSUE TITLE
I am getting Windows Error 3

### ISSUE THREAD

**Issue by garyrusso** [DanWahlin/Angular-RESTfulService#3]
I'm getting the following Windows Error 3 message whenever I attempt the "docker-compose build" command.

Here the output error message.

```
$ docker-compose build
Building node
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 61, in main
  File "compose\cli\main.py", line 113, in perform_command
  File "compose\cli\main.py", line 219, in build
  File "compose\project.py", line 300, in build
  File "compose\service.py", line 727, in build
  File "site-packages\docker\api\build.py", line 54, in build
  File "site-packages\docker\utils\utils.py", line 103, in tar
  File "tarfile.py", line 2006, in add
  File "tarfile.py", line 1878, in gettarinfo
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\projects\\Angular2-RESTfulService\\node_modules\\systemjs-builder\\node_modules\\babel-plugin-transform-cjs-system-wrapper\\node_modules\\babel-template\\node_modules\\babel-traverse\\node_modules\\babel-code-frame\\node_modules\\chalk\\node_modules\\ansi-styles\\package.json'
docker-compose returned -1
```

**Comment by DanWahlin** [comment]
Try running it from a folder under "Users" (such as your Desktop) first. Docker restricts what folders are allowed to be used.
